### ISSUE TITLE
Build a page for this.

### ISSUE THREAD

**Issue by scottonanski** [jameshibbard/demo-node-app#13]
Kind of pointless to have a tutorial on how to building something and not show the end product. I mean, think about it;

People are coming to your tutorial to learn how to do something they  don't already know. You offer an opportunity for them to see what they'll be working on. When they click your link, then end up looking at something they don't know anything about, which is why they sought out your tutorial in the first place!

It only takes a few seconds to set up a page, and ironically enough, there's documentation on Github on how to do that.

**Comment by jameshibbard** [comment]
Thanks for your comments. I agree that it would be nice to get an idea of what is being built when starting the article.

One reason for not implementing this, is that it is a database backed application and were we to let users input whatever they liked into said db, there would need to be a mechanism in place to periodically scrub the database and reseed it (for example if someone entered something offensive or profane).

> It only takes a few seconds to set up a page

I disagree with this. At the minimum you need a Node runtime (preferably the same version as is used in the article) and a MongoDB instance. While this is not overly difficult to set up, it takes more than a few seconds.

This is also why I have provided detailed instructions on how readers can run the code on their own machines. Did you try this? Was there a particular step that you are having trouble with?
